import type { ConfirmedProjectIdentity } from "../domain/project-identity";
import type { OnchainArtifact, OnchainProvenance, OnchainResult } from "./providers/onchain-types";

// AMENDMENT C — entity binding for a structured artifact is decided by the
// ARTIFACT's own validated fields, never by its URI.
//
// The canonical URI is generated by our own code from the same intent that
// produced the request. Accepting it as proof would be circular: it would
// only ever confirm that we asked for what we asked for. Binding therefore
// re-derives agreement from four independent places, and every one of them
// must hold:
//
//   1. chain and network match the project's confirmed identity
//   2. the artifact's project anchor IS the confirmed identity address
//   3. the subject stands in a declared relationship to that anchor
//   4. the normalized RPC RESPONSE names the subject it claims to describe
//
// (4) is what makes this more than bookkeeping: a provider that returns
// data about a different mint, account or transaction than the one asked
// for fails here even though (1)-(3) were composed correctly by us.
//
// Fail-closed throughout: an unknown result shape, a missing field, or any
// disagreement yields UNVERIFIED. Nothing is assumed compatible.

export type OnchainBindingOutcome =
  | { binding: "CONFIRMED" }
  | { binding: "UNVERIFIED"; reason: OnchainBindingFailure };

export type OnchainBindingFailure =
  | "NO_CONFIRMED_IDENTITY"
  | "CHAIN_MISMATCH"
  | "NETWORK_NOT_PRODUCTION"
  | "ANCHOR_NOT_PROJECT_IDENTITY"
  | "SUBJECT_RELATIONSHIP_UNDECLARED"
  | "RESPONSE_SUBJECT_MISMATCH"
  | "PROVENANCE_INCOMPLETE";

// Solana base58 is case-significant; an EVM adapter would compare
// case-insensitively (EIP-55). Kept here so the rule is stated once and
// the future adapter has an obvious place to extend rather than a hidden
// assumption to discover.
function addressesEqual(chain: string, a: string, b: string): boolean {
  return chain === "solana" ? a === b : a.toLowerCase() === b.toLowerCase();
}

// Complete provenance is an ELIGIBILITY prerequisite, not a nicety: an
// observation nobody can re-verify cannot be allowed to establish a claim.
export function isProvenanceComplete(p: OnchainProvenance | null | undefined): boolean {
  if (!p) return false;
  return (
    typeof p.chain === "string" &&
    typeof p.network === "string" &&
    typeof p.projectAnchor === "string" &&
    p.projectAnchor.length > 0 &&
    typeof p.subject === "string" &&
    p.subject.length > 0 &&
    Number.isInteger(p.slot) &&
    p.slot >= 0 &&
    (p.finality === "finalized" || p.finality === "confirmed") &&
    p.retrievalMethod === "RPC" &&
    typeof p.providerId === "string" &&
    p.providerId.length > 0 &&
    typeof p.providerMethod === "string" &&
    p.providerMethod.length > 0 &&
    p.retrievedAt instanceof Date &&
    !Number.isNaN(p.retrievedAt.getTime()) &&
    typeof p.rawResponseHash === "string" &&
    p.rawResponseHash.length > 0 &&
    typeof p.artifactHash === "string" &&
    p.artifactHash.length > 0
  );
}

// Which address the normalized RESPONSE says it is about. Returns null
// when the shape carries no subject to check — treated as a mismatch
// rather than a pass, so a new result kind cannot be added and silently
// skip this check.
function responseSubject(result: OnchainResult): string | null {
  switch (result.kind) {
    case "TOKEN_SUPPLY":
      return result.mint;
    case "ACCOUNT_INFO":
      return result.address;
    case "TOKEN_ACCOUNT_BALANCE":
      return result.account;
    case "SIGNATURES_FOR_ADDRESS":
      return result.address;
    case "TRANSACTION_DETAIL":
      return result.signature;
    default:
      return null;
  }
}

// Is the subject's relationship to the project anchor one this design
// declares? AMENDMENT D: a derived subject (an account, a transaction) is
// only ever admitted through an intent the caller had to justify with
// admitted provenance — this function confirms the relationship is a
// declared kind, and the caller is responsible for how the subject was
// obtained.
function subjectRelationshipDeclared(artifact: OnchainArtifact): boolean {
  const { intent } = artifact;
  switch (intent.subjectKind) {
    case "token":
      // A direct token read must be about the anchor itself.
      return addressesEqual(intent.chain, intent.subject, intent.projectAnchor);
    case "account":
    case "tx":
      // A derived subject is distinct from the anchor by definition; both
      // are preserved so the relationship stays inspectable.
      return intent.subject.length > 0 && intent.projectAnchor.length > 0;
    default:
      return false;
  }
}

export function validateOnchainBinding(
  artifact: OnchainArtifact,
  identity: ConfirmedProjectIdentity | null,
): OnchainBindingOutcome {
  if (!identity?.tokenAddress) {
    return { binding: "UNVERIFIED", reason: "NO_CONFIRMED_IDENTITY" };
  }
  const p = artifact.provenance;
  if (!isProvenanceComplete(p)) {
    return { binding: "UNVERIFIED", reason: "PROVENANCE_INCOMPLETE" };
  }
  if (p.chain !== identity.chain || artifact.intent.chain !== identity.chain) {
    return { binding: "UNVERIFIED", reason: "CHAIN_MISMATCH" };
  }
  // D-131 — production only. v1 models no test network at all, so any
  // other value is rejected rather than ranked lower.
  if (p.network !== "mainnet" || artifact.intent.network !== "mainnet") {
    return { binding: "UNVERIFIED", reason: "NETWORK_NOT_PRODUCTION" };
  }
  if (!addressesEqual(p.chain, p.projectAnchor, identity.tokenAddress)) {
    return { binding: "UNVERIFIED", reason: "ANCHOR_NOT_PROJECT_IDENTITY" };
  }
  if (!subjectRelationshipDeclared(artifact)) {
    return { binding: "UNVERIFIED", reason: "SUBJECT_RELATIONSHIP_UNDECLARED" };
  }
  // The independent check: the provider's own normalized answer must be
  // about the subject we asked for.
  const claimed = responseSubject(artifact.result);
  if (claimed === null || !addressesEqual(p.chain, claimed, artifact.intent.subject)) {
    return { binding: "UNVERIFIED", reason: "RESPONSE_SUBJECT_MISMATCH" };
  }
  return { binding: "CONFIRMED" };
}
