import {
  InterpreterUnavailableError,
  type InterpreterCall,
  type InterpreterGateway,
  type InterpreterInput,
} from "./gateway";
import { parseInterpreterResult, type InterpreterModelResult } from "./schema";

// Детерминированный gateway для тестов/dev/CI без API-ключа.
// Это НЕ «подставим ответ, если API недоступен»: реализация выбирается
// явным MODEL_GATEWAY=fake и запрещена в production (gateway.ts).
// Контракт тот же: результат проходит ту же валидацию схемы.

type Script = (input: InterpreterInput) => unknown;

const scripts: Script[] = [];

// Тестовый сценарий на один вызов: очередь ответов «как если бы модель
// вернула вот это» — включая заведомо испорченные, чтобы проверить,
// что сервер их не пропускает.
export function __pushFakeScript(s: Script): void {
  scripts.push(s);
}

export function __clearFakeScripts(): void {
  scripts.length = 0;
}

let failOnce = 0;

// Имитация инфраструктурного сбоя провайдера (для теста retry-политики).
export function __failNextCalls(n: number): void {
  failOnce = n;
}

const KNOWN_ASSETS = [
  "pump.fun",
  "pumpfun",
  "pump fun",
  "hyperliquid",
  "uniswap",
  "aave",
  "sui",
  "tao",
  "bitcoin",
];

const base = (): InterpreterModelResult => ({
  status: "INVALID",
  project_or_asset: null,
  topic: null,
  task_type: null,
  research_task: null,
  user_assumptions: [],
  ambiguities: [],
  clarification_question: null,
  route: "OUTSIDE_CURRENT_DOMAIN",
  normalized_intent: "UNKNOWN",
  intent_confidence: 0.2,
  route_reason: "fake gateway",
  needs_fresh_evidence: false,
  quick_answer: null,
});

function findAsset(text: string): string | null {
  const lower = text.toLowerCase();
  return KNOWN_ASSETS.find((a) => lower.includes(a)) ?? null;
}

function decide(input: InterpreterInput): InterpreterModelResult {
  const all = [
    input.question,
    ...input.clarificationTurns.map((t) => t.answer),
  ].join(" ");
  const lower = all.toLowerCase();
  const r = base();

  if (/ignore (all )?previous|system prompt|you are now|act as/i.test(lower)) {
    return { ...r, route_reason: "no research task in instruction-like input" };
  }
  if (all.trim().length < 3 || !/[a-zа-я]/i.test(all)) {
    return { ...r, route_reason: "no meaningful content" };
  }
  if (/(луне|moon).*(интернет|internet)|(интернет|internet).*(луне|moon)/.test(lower)) {
    return {
      ...r,
      status: "READY",
      route: "NO_RESEARCH_NEEDED",
      project_or_asset: findAsset(all),
      task_type: "OTHER_RESEARCH",
      research_task: "No established causal link to research.",
      normalized_intent: "SCENARIO_CAUSAL_IMPACT",
      intent_confidence: 0.9,
      route_reason: "no established causal link",
      quick_answer: "Такой связи не существует — исследовать здесь нечего.",
    };
  }
  if (/staking|стейкинг/.test(lower) && /(safe|безопас|надёж|надеж)/.test(lower)) {
    return {
      ...r,
      status: "READY",
      route: "QUICK_EXPLANATION",
      project_or_asset: findAsset(all),
      topic: "Token Value Capture",
      task_type: "EXPLANATION",
      research_task: "Explain the category difference between staking and safety.",
      normalized_intent: "TOKEN_UTILITY",
      intent_confidence: 0.8,
      route_reason: "category mistake",
      quick_answer:
        "Наличие стейкинга не говорит о безопасности проекта: это разные категории.",
    };
  }
  if (/(погод|weather|футбол|football|рецепт)/.test(lower)) {
    return {
      ...r,
      status: "OUT_OF_SCOPE",
      route: "OUTSIDE_CURRENT_DOMAIN",
      route_reason: "outside Token Value Capture",
    };
  }

  const asset = findAsset(all);
  if (!asset) {
    return {
      ...r,
      status: "NEEDS_CLARIFICATION",
      route: "CLARIFICATION_REQUIRED",
      topic: "Token Value Capture",
      ambiguities: ["project is not named"],
      clarification_question: "О каком проекте или токене идёт речь?",
      normalized_intent: "UNKNOWN",
      intent_confidence: 0.4,
      route_reason: "project not named",
    };
  }

  const isComparison = /(сравн|compare|vs\b|против)/.test(lower);
  return {
    ...r,
    status: "READY",
    route: "DEEP_RESEARCH",
    project_or_asset: asset,
    topic: "Token Value Capture",
    task_type: isComparison ? "COMPARISON" : "TOKEN_VALUE",
    research_task: `Determine whether and how value generated by ${asset} reaches token holders.`,
    user_assumptions: /зарабатыва|revenue|доход/.test(lower)
      ? ["the project generates revenue"]
      : [],
    normalized_intent: "PROTOCOL_REVENUE_TO_TOKEN",
    intent_confidence: 0.85,
    route_reason: "mechanism question within the trained domain",
    needs_fresh_evidence: true,
  };
}

export const fakeGateway: InterpreterGateway = {
  name: "fake",
  async interpret(input: InterpreterInput, model: string): Promise<InterpreterCall> {
    if (failOnce > 0) {
      failOnce -= 1;
      throw new InterpreterUnavailableError("fake failure");
    }
    const script = scripts.shift();
    const raw = script ? script(input) : decide(input);
    return {
      result: parseInterpreterResult(raw),
      meta: {
        gateway: "fake",
        model,
        inputTokens: null,
        outputTokens: null,
        latencyMs: 0,
      },
    };
  },
};
