import type { GoldenScenario } from "./evaluation";

// Единый источник для acceptance-контуров, использующих golden set:
// tests/phase5-evaluation.test.ts И scripts/eval-memory.ts читают отсюда —
// один список сценариев, ни один не пересчитывает другой. Исходные 8 углов
// (phase-5-plan.md §7.4) сохранены как регрессия; ниже добавлены углы,
// требуемые пакетом исправлений ревью (D-058..D-066, MEDIUM-1).

const NOW = new Date();
const FRESH = new Date(NOW.getTime() - 1 * 24 * 60 * 60 * 1000);
const STALE_HIGH_CHANGE = new Date(NOW.getTime() - 30 * 24 * 60 * 60 * 1000); // > default 3d stale_after

export const GOLDEN_SCENARIOS: GoldenScenario[] = [
  {
    name: "norm: свежее знание закрывает часть шагов",
    angle: "norm",
    capability: "FRESH_RESEARCH",
    statementQuery: "does protocol revenue reach token holders",
    seedFacts: [
      {
        patternStep: 1,
        component: "SOURCE_OF_VALUE",
        claimKey: "economic_source",
        statement: "swap fee is the source",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 2,
        component: "FLOW_PATH",
        claimKey: "revenue_waterfall",
        statement: "fees flow to treasury first",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 92,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 3,
        component: "MECHANISM_SPEC",
        claimKey: "allocation_mechanism",
        statement: "governance-approved buyback",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: FRESH,
        confidence: 90,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 3,
        component: "GOVERNANCE_BASIS",
        claimKey: "allocation_governance",
        statement: "approved by on-chain governance vote",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: FRESH,
        confidence: 90,
        promote: true,
        reusable: true,
      },
    ],
    expectedSatisfiedSteps: [1, 2, 3],
  },
  {
    name: "completeness: памяти нет вовсе",
    angle: "completeness",
    capability: "FRESH_RESEARCH",
    statementQuery: "does protocol revenue reach token holders",
    seedFacts: [],
    expectedSatisfiedSteps: [],
  },
  {
    name: "freshness: динамический факт просрочен",
    angle: "freshness",
    capability: "FRESH_RESEARCH",
    statementQuery: "is the buyback mechanism currently active",
    seedFacts: [
      {
        patternStep: 5,
        component: "CURRENT_STATE",
        claimKey: "current_status",
        statement: "status checked long ago",
        freshnessClass: "HIGH_CHANGE",
        verifiedAt: STALE_HIGH_CHANGE,
        confidence: 99,
        promote: true,
        reusable: false,
        invalidReason: "STALE",
      },
    ],
    expectedSatisfiedSteps: [], // просрочен -> required_fresh, НЕ already_satisfied
  },
  {
    name: "sufficiency: всё свежо и покрыто",
    angle: "sufficiency",
    capability: "FRESH_RESEARCH",
    statementQuery: "full value capture review",
    seedFacts: [
      {
        patternStep: 1,
        component: "SOURCE_OF_VALUE",
        claimKey: "step_1_claim",
        statement: "verified fact for step 1",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 2,
        component: "FLOW_PATH",
        claimKey: "step_2_claim",
        statement: "verified fact for step 2",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 3,
        component: "MECHANISM_SPEC",
        claimKey: "step_3_claim_a",
        statement: "verified fact for step 3 mechanism",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 3,
        component: "GOVERNANCE_BASIS",
        claimKey: "step_3_claim_b",
        statement: "verified fact for step 3 governance",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 4,
        component: "EXECUTION_EVIDENCE",
        claimKey: "step_4_claim",
        statement: "verified fact for step 4",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 5,
        component: "CURRENT_STATE",
        claimKey: "step_5_claim",
        statement: "verified fact for step 5",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 6,
        component: "DESTINATION",
        claimKey: "step_6_claim_a",
        statement: "verified fact for step 6 destination",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 6,
        component: "RECIPIENT",
        claimKey: "step_6_claim_b",
        statement: "verified fact for step 6 recipient",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 7,
        component: "NET_EFFECT",
        claimKey: "step_7_claim",
        statement: "verified fact for step 7",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
      {
        patternStep: 8,
        component: "DURABILITY_BASIS",
        claimKey: "step_8_claim",
        statement: "verified fact for step 8",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
    ],
    expectedSatisfiedSteps: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    name: "capability boundary: DEMO не получает FRESH_RESEARCH",
    angle: "capability_boundary",
    capability: "TARGETED_REFRESH",
    statementQuery: "brand new project, nothing known",
    seedFacts: [],
    expectedSatisfiedSteps: [],
  },
  {
    name: "wording: другая формулировка того же claim",
    angle: "wording",
    capability: "FRESH_RESEARCH",
    statementQuery: "does the project burn revenue into the token supply",
    seedFacts: [
      {
        patternStep: 7,
        component: "NET_EFFECT",
        claimKey: "net_token_effect",
        statement:
          "Half of protocol revenue is used to burn the token every epoch",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: FRESH,
        confidence: 88,
        promote: true,
        reusable: true,
      },
    ],
    expectedSatisfiedSteps: [7],
  },
  {
    name: "poisoning: заведомо непроверенное знание не закрывает шаг",
    angle: "poisoning",
    capability: "FRESH_RESEARCH",
    statementQuery: "was the buyback actually executed",
    seedFacts: [
      {
        patternStep: 4,
        component: "EXECUTION_EVIDENCE",
        claimKey: "actual_execution",
        statement: "PLANTED: buyback executed (unverified)",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 99,
        promote: false,
        reusable: false,
        invalidReason: "UNPROMOTED",
      },
    ],
    expectedSatisfiedSteps: [], // не промоутнут -> CANDIDATE -> невидим retrieval
  },
  {
    name: "чужой проект: память проекта A не закрывает шаг проекта B",
    angle: "cross_project",
    capability: "FRESH_RESEARCH",
    statementQuery: "durability of the mechanism",
    seedFacts: [],
    foreignProjectSeedFacts: [
      {
        patternStep: 8,
        component: "DURABILITY_BASIS",
        claimKey: "durability",
        statement: "durable per foreign project's governance",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: false,
        invalidReason: "WRONG_PROJECT",
      },
    ],
    expectedSatisfiedSteps: [],
  },

  // --- Пакет исправлений ревью: новые углы (D-058..D-066, MEDIUM-1) ---

  {
    name: "D-058 regression: DEMO, 1 закрытый шаг из 8, 7 MISSING всё равно требуют FRESH_RESEARCH",
    angle: "capability_boundary",
    capability: "TARGETED_REFRESH", // DEMO — тот же потолок, что и в исходном capability_boundary сценарии
    statementQuery: "full value capture review, mostly unknown",
    seedFacts: [
      {
        patternStep: 1,
        component: "SOURCE_OF_VALUE",
        claimKey: "d058_step_1",
        statement: "verified economic source",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        reusable: true,
      },
    ],
    // Шаги 2..8 без памяти -> MISSING. Старый баг (satisfied.length===0 &&
    // requiredFresh.length===0 -> FRESH_RESEARCH) требовал ВСЕ шаги
    // незакрытыми, чтобы дойти до FRESH_RESEARCH — с одним закрытым шагом
    // он ошибочно давал TARGETED_REFRESH и НЕ упирался в потолок. Здесь
    // missing.length=7>0, значит desiredMode обязан быть FRESH_RESEARCH и
    // capabilityCeilingHit обязан сработать, несмотря на закрытый шаг 1.
    expectedSatisfiedSteps: [1],
  },

  {
    name: "D-059 health QUESTIONABLE: не закрывает шаг, но найдено",
    angle: "health",
    capability: "FRESH_RESEARCH",
    statementQuery: "questionable health check",
    seedFacts: [
      {
        patternStep: 2,
        component: "FLOW_PATH",
        claimKey: "health_questionable",
        statement: "flow path fact under review",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        health: "QUESTIONABLE",
        reusable: false,
        invalidReason: "UNHEALTHY",
      },
    ],
    expectedSatisfiedSteps: [],
  },
  {
    name: "D-059 health REVERIFY: не закрывает шаг, но найдено",
    angle: "health",
    capability: "FRESH_RESEARCH",
    statementQuery: "reverify health check",
    seedFacts: [
      {
        patternStep: 2,
        component: "FLOW_PATH",
        claimKey: "health_reverify",
        statement: "flow path fact flagged for reverification",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        health: "REVERIFY",
        reusable: false,
        invalidReason: "UNHEALTHY",
      },
    ],
    expectedSatisfiedSteps: [],
  },
  {
    name: "D-059 health STALE: не закрывает шаг, но найдено",
    angle: "health",
    capability: "FRESH_RESEARCH",
    statementQuery: "stale health check",
    seedFacts: [
      {
        patternStep: 2,
        component: "FLOW_PATH",
        claimKey: "health_stale",
        statement: "flow path fact marked stale by health",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        health: "STALE",
        reusable: false,
        invalidReason: "UNHEALTHY",
      },
    ],
    expectedSatisfiedSteps: [],
  },
  {
    name: "D-059 health DEPRECATED: исключён из retrieval полностью",
    angle: "health",
    capability: "FRESH_RESEARCH",
    statementQuery: "deprecated health check",
    seedFacts: [
      {
        patternStep: 2,
        component: "FLOW_PATH",
        claimKey: "health_deprecated",
        statement: "flow path fact deprecated",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: FRESH,
        confidence: 95,
        promote: true,
        health: "DEPRECATED",
        reusable: false,
        invalidReason: "UNHEALTHY",
      },
    ],
    expectedSatisfiedSteps: [],
  },

  {
    name: "MEDIUM-1: stale_after = 36 часов, факт внутри окна",
    angle: "stale_after_interval",
    capability: "FRESH_RESEARCH",
    statementQuery: "36 hour freshness window",
    seedFacts: [
      {
        patternStep: 5,
        component: "CURRENT_STATE",
        claimKey: "stale_after_36h",
        statement: "checked 10 hours ago, policy allows 36 hours",
        freshnessClass: "HIGH_CHANGE",
        verifiedAt: new Date(NOW.getTime() - 10 * 60 * 60 * 1000),
        staleAfter: "36 hours",
        confidence: 95,
        promote: true,
        reusable: true,
      },
    ],
    // EXTRACT(DAY FROM '36 hours'::interval) = 0 под старым багом -> факт
    // ошибочно считался бы просроченным несмотря на возраст 10ч < 36ч.
    expectedSatisfiedSteps: [5],
  },
  {
    name: "MEDIUM-1: stale_after = 3 месяца, факт внутри окна",
    angle: "stale_after_interval",
    capability: "FRESH_RESEARCH",
    statementQuery: "3 month freshness window",
    seedFacts: [
      {
        patternStep: 5,
        component: "CURRENT_STATE",
        claimKey: "stale_after_3mo",
        statement: "checked 30 days ago, policy allows 3 months",
        freshnessClass: "LOW_CHANGE",
        verifiedAt: new Date(NOW.getTime() - 30 * 24 * 60 * 60 * 1000),
        staleAfter: "3 months",
        confidence: 95,
        promote: true,
        reusable: true,
      },
    ],
    // EXTRACT(DAY FROM '3 months'::interval) = 0 под старым багом (месяцы
    // хранятся отдельным полем interval, не днями) -> факт ошибочно считался
    // бы просроченным несмотря на возраст 30д внутри трёхмесячного окна.
    expectedSatisfiedSteps: [5],
  },
  {
    name: "MEDIUM-1: stale_after = 2 дня 3 часа (не целые сутки), факт внутри окна",
    angle: "stale_after_interval",
    capability: "FRESH_RESEARCH",
    statementQuery: "non-whole-day freshness window",
    seedFacts: [
      {
        patternStep: 5,
        component: "CURRENT_STATE",
        claimKey: "stale_after_odd_interval",
        statement: "checked 1 day ago, policy allows 2 days 3 hours",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: new Date(NOW.getTime() - 1 * 24 * 60 * 60 * 1000),
        staleAfter: "2 days 3 hours",
        confidence: 95,
        promote: true,
        reusable: true,
      },
    ],
    expectedSatisfiedSteps: [5],
  },

  {
    name: "D-060 partial coverage: один из двух требуемых компонентов шага 3 не покрыт",
    angle: "partial_coverage",
    capability: "FRESH_RESEARCH",
    statementQuery: "allocation mechanism spec only, no governance basis",
    seedFacts: [
      {
        patternStep: 3,
        component: "MECHANISM_SPEC",
        claimKey: "partial_mechanism_spec",
        statement: "mechanism described but not sanctioned",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: FRESH,
        confidence: 90,
        promote: true,
        reusable: true,
      },
      // GOVERNANCE_BASIS сознательно не посеян — шаг 3 обязан остаться
      // REQUIRED_FRESH (частичное покрытие), а НЕ ALREADY_SATISFIED.
    ],
    expectedSatisfiedSteps: [],
  },

  {
    name: "D-062 contradiction: два ACTIVE факта с разным mechanism_state для одного компонента",
    angle: "contradiction",
    capability: "FRESH_RESEARCH",
    statementQuery: "conflicting mechanism state for allocation",
    seedFacts: [
      {
        patternStep: 3,
        component: "MECHANISM_SPEC",
        claimKey: "contradiction_a",
        statement: "mechanism is buyback only",
        mechanismState: "BUYBACK_ONLY",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: FRESH,
        confidence: 90,
        promote: true,
        reusable: false,
        invalidReason: "CONTRADICTED",
      },
      {
        patternStep: 3,
        component: "MECHANISM_SPEC",
        claimKey: "contradiction_b",
        statement: "mechanism is buyback and burn",
        mechanismState: "BUYBACK_AND_BURN",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: FRESH,
        confidence: 90,
        promote: true,
        reusable: false,
        invalidReason: "CONTRADICTED",
      },
      {
        patternStep: 3,
        component: "GOVERNANCE_BASIS",
        claimKey: "contradiction_governance",
        statement: "approved by governance",
        freshnessClass: "MEDIUM_CHANGE",
        verifiedAt: FRESH,
        confidence: 90,
        promote: true,
        reusable: true,
      },
    ],
    // GOVERNANCE_BASIS сам по себе закрыт, но MECHANISM_SPEC противоречив ->
    // шаг 3 целиком обязан остаться REQUIRED_FRESH, а не ALREADY_SATISFIED.
    expectedSatisfiedSteps: [],
  },
];
